import * as React from 'react';

import { cleanup, screen, setup } from '@/lib/test-utils';
import { ChapterReaderScreen } from './chapter-reader-screen';

/**
 * AI-content labeling (issue #12): the child-facing reader should also carry
 * the disclosure, on the title page, in whichever language leads for that
 * child — and here it can honestly say a parent already reviewed it, since
 * nothing reaches the reader unapproved (the parent-preview gate).
 */

const mockUseChapterReader = jest.fn();

jest.mock('expo-router', () => ({
  useLocalSearchParams: () => ({ id: 'chapter-1' }),
  useRouter: () => ({ back: jest.fn(), replace: jest.fn() }),
}));

jest.mock('@/features/reader/use-chapter-reader', () => ({
  useChapterReader: (...args: unknown[]) => mockUseChapterReader(...args),
}));

afterEach(() => {
  cleanup();
  jest.clearAllMocks();
});

function baseReader(overrides: Partial<ReturnType<typeof mockUseChapterReader>> = {}) {
  return {
    chapter: {
      id: 'chapter-1',
      title_en: 'The Quiet Forest',
      title_ko: '조용한 숲',
      pages: [{ page: 1, en: 'Once upon a time.', ko: '옛날 옛적에.' }],
    },
    lead: 'en',
    name: 'Mia',
    index: 0,
    finished: false,
    loading: false,
    busy: false,
    error: null,
    offline: false,
    next: jest.fn(),
    previous: jest.fn(),
    queueTomorrow: jest.fn(),
    imageUrlFor: () => undefined,
    ...overrides,
  };
}

describe('chapterReaderScreen — AI-content labeling', () => {
  it('shows the reviewed-by-a-parent AI notice on the title page, English-led', () => {
    mockUseChapterReader.mockReturnValue(baseReader());
    setup(<ChapterReaderScreen />);

    expect(screen.getByTestId('ai-generated-notice')).toBeOnTheScreen();
    expect(
      screen.getByText(/Made with AI — text and pictures generated by AI, reviewed by a parent\./),
    ).toBeOnTheScreen();
    expect(
      screen.getByText('AI로 만들었어요 — 글과 그림을 AI가 만들었고, 부모님이 확인했어요.'),
    ).toBeOnTheScreen();
  });

  it('leads with Korean for a Korean-primary child, both languages still present', () => {
    mockUseChapterReader.mockReturnValue(baseReader({ lead: 'ko' }));
    setup(<ChapterReaderScreen />);

    expect(
      screen.getByText('AI로 만들었어요 — 글과 그림을 AI가 만들었고, 부모님이 확인했어요.'),
    ).toBeOnTheScreen();
    expect(
      screen.getByText(/Made with AI — text and pictures generated by AI, reviewed by a parent\./),
    ).toBeOnTheScreen();
  });
});
