#!/usr/bin/env python3
"""Spike B harness — cross-night memory, bilingual.

Each chapter is generated by a SEPARATE process invoking the stateless
generate-chapter Edge Function. The function builds a fresh Anthropic client per
request and feeds it nothing but canon retrieved from Postgres, so there is no
conversational carry-over between chapters by construction. That is the property
under test.
"""
import json
import pathlib
import time
import urllib.error
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]

# Seeded by hand for the spike: Mia, age band 5-6, primary language ko.
CHILD_ID = "6cc02daf-bfae-4e51-8254-f53fd725f9ba"


def env(name):
    for line in (REPO / ".env").read_text().splitlines():
        if line.startswith(name + "="):
            return line.split("=", 1)[1].strip()
    raise SystemExit(f"{name} not in .env")


BASE, ANON = env("EXPO_PUBLIC_SUPABASE_URL"), env("EXPO_PUBLIC_SUPABASE_ANON_KEY")


def generate(slug, lesson, situation=None):
    """Invoke generate-chapter and save the full response + a readable render."""
    payload = {"child_id": CHILD_ID, "lesson": lesson, "debug_canon": True}
    if situation:
        payload["situation"] = situation

    # Saved verbatim so the experiment is auditable: chapter 2's request must
    # contain no trace of chapter 1's content.
    (HERE / f"{slug}.request.json").write_text(json.dumps(payload, indent=2, ensure_ascii=False))

    req = urllib.request.Request(
        f"{BASE}/functions/v1/generate-chapter",
        data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {ANON}", "Content-Type": "application/json"},
        method="POST",
    )
    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=900) as r:
            body = json.loads(r.read())
    except urllib.error.HTTPError as e:
        raw = e.read().decode(errors="replace")
        try:
            body = json.loads(raw)
        except Exception:
            body = {"ok": False, "error": f"HTTP {e.code}: {raw[:2000]}"}
    wall = time.time() - started

    if not body.get("ok"):
        print(f"FAIL {slug}: {str(body.get('error'))[:900]}")
        return None

    (HERE / f"{slug}.json").write_text(json.dumps(body, indent=2, ensure_ascii=False))
    render(slug, body)

    ch = body["chapter"]
    print(f"ok  {slug}: ch.{body['number']} \"{ch['title_en']}\" / \"{ch['title_ko']}\"")
    print(f"    {len(ch['pages'])} pages · {body['latency_ms']/1000:.1f}s api · {wall:.1f}s wall")
    print(f"    threads opened={len(ch['delta']['threads_opened'])} "
          f"resolved={len(ch['delta']['threads_resolved'])}")
    return body


def render(slug, body):
    """Write the chapter as page-aligned bilingual markdown."""
    ch, canon = body["chapter"], body.get("retrieved_canon", {})
    out = [
        f"# Chapter {body['number']} — {ch['title_en']}",
        f"## {ch['title_ko']}",
        "",
        f"*Lesson: {json.loads((HERE / f'{slug}.request.json').read_text())['lesson']}*",
        "",
        "**English summary (canonical, drives retrieval):**",
        f"> {ch['summary']}",
        "",
        "---",
        "",
        "## Canon retrieved from Postgres before writing",
        "",
        "This is the model's ENTIRE memory of the story — no chat history.",
        "",
        "```",
        body.get("canon_prompt", "(not captured)"),
        "```",
        "",
        "---",
        "",
        "## Pages",
        "",
    ]
    for p in ch["pages"]:
        out += [
            f"### Page {p['page']}",
            "",
            f"**EN** — {p['en']}",
            "",
            f"**KO** — {p['ko']}",
            "",
            f"<sub>scene: {p['scene']}</sub>  ",
            f"<sub>wardrobe: {p['wardrobe']}</sub>",
            "",
        ]

    d = ch["delta"]
    out += ["---", "", "## Story Bible delta", "", "```json",
            json.dumps(d, indent=2, ensure_ascii=False), "```", ""]
    if canon:
        out += [f"<sub>Retrieved {len(canon.get('recent_chapters', []))} prior chapter(s), "
                f"{len(canon.get('open_threads', []))} open thread(s), "
                f"{len(canon.get('characters', []))} character(s).</sub>", ""]

    (HERE / f"{slug}.md").write_text("\n".join(out))
