#!/usr/bin/env python3
"""Spike C — unit economics model.

Every input is a MEASURED number from Spike A or Spike B, not an estimate.
Re-run after changing an assumption; it rewrites README tables via stdout.

  python3 cost_model.py
"""

# --- measured inputs -------------------------------------------------------
# Spike B: docs/spikes/spike-b/chapter-{1,2}.json
TEXT_COST_PER_CHAPTER = 0.136   # claude-opus-5, 8 pages EN+KO
TEXT_SECONDS = 71

# Spike A: docs/spikes/spike-a/nano-banana/costs.md
IMAGE_COST = 0.0391             # gemini-2.5-flash-image, per image
IMAGE_SECONDS = 8.8
IMAGE_COST_PRO = 0.1350         # gemini-3-pro-image, for the keepsake tier

# Spike D: an independent safety pass over the text, plus a vision pass per
# illustration. Never sampled — it runs on everything.
TEXT_SAFETY_COST = 0.02
IMAGE_SAFETY_COST = 0.01

# --- product shape (ADR-0002) ----------------------------------------------
PAGES_DEFAULT = 6               # 5-8 short bilingual text pages
IMAGES_DEFAULT = 4              # ~4 of them carry art: the emotional beats
NIGHTS_PER_MONTH = 30           # the pitch is nightly

# Phase-2 open-weights target. NOT measured — REPLICATE_API_TOKEN is unset, so
# the path-2 spike has not run. Shown only to size the prize.
IMAGE_COST_OPENWEIGHTS_TARGET = 0.013

# --- distribution ----------------------------------------------------------
# Apple/Google take 15% under their small-business programmes (<$1M/yr), 30%
# above. RevenueCat is free below $2.5k/mo tracked revenue.
STORE_CUT_SMALL = 0.15
STORE_CUT_STANDARD = 0.30


def chapter_cost(pages=PAGES_DEFAULT, images=None, image_cost=IMAGE_COST,
                 text_cost=TEXT_COST_PER_CHAPTER):
    """Cost of one chapter. `images` defaults to one per page."""
    images = pages if images is None else images
    return (
        text_cost
        + TEXT_SAFETY_COST
        + images * (image_cost + IMAGE_SAFETY_COST)
    )


def chapter_seconds(pages=PAGES_DEFAULT, images=None, parallel=True):
    images = pages if images is None else images
    img = IMAGE_SECONDS if parallel else IMAGE_SECONDS * images
    return TEXT_SECONDS + img


def monthly_cost(chapters, **kw):
    return chapters * chapter_cost(**kw)


def margin(price, chapters, store_cut, **kw):
    net = price * (1 - store_cut)
    cost = monthly_cost(chapters, **kw)
    return net, cost, net - cost, (net - cost) / net if net else 0


def table(title, rows, headers):
    print(f"\n### {title}\n")
    print("| " + " | ".join(headers) + " |")
    print("|" + "|".join(["---"] * len(headers)) + "|")
    for r in rows:
        print("| " + " | ".join(str(c) for c in r) + " |")


if __name__ == "__main__":
    print("# Spike C — computed tables (generated by cost_model.py)")

    # 1. What one chapter costs, by shape.
    shapes = [
        ("8 pages, 8 images (as generated in Spike B)", 8, 8),
        ("6 pages, 6 images", 6, 6),
        ("5 pages, 5 images", 5, 5),
        ("8 pages, 4 spot illustrations", 8, 4),
        ("6 pages, 3 spot illustrations", 6, 3),
    ]
    rows = []
    for label, pages, images in shapes:
        c = chapter_cost(pages, images)
        rows.append((label, f"${c:.3f}",
                     f"${c*NIGHTS_PER_MONTH:.2f}",
                     f"{chapter_seconds(pages, images):.0f}s"))
    table("Cost per chapter by shape", rows,
          ["Shape", "$/chapter", "$/mo if nightly", "Latency (parallel images)"])

    # 2. Margin at candidate prices, nightly user, default shape.
    rows = []
    for price in (9.99, 12.99, 14.99, 19.99):
        for cut, cutname in ((STORE_CUT_SMALL, "15%"), (STORE_CUT_STANDARD, "30%")):
            net, cost, gross, pct = margin(price, NIGHTS_PER_MONTH, cut)
            rows.append((f"${price}", cutname, f"${net:.2f}", f"${cost:.2f}",
                         f"${gross:.2f}", f"{pct*100:.0f}%"))
    table(f"Margin for a NIGHTLY user ({NIGHTS_PER_MONTH} chapters, 8 pages/8 images)",
          rows, ["Price/mo", "Store cut", "Net revenue", "Cost", "Gross", "Margin"])

    # 3. Break-even chapter counts.
    rows = []
    for price in (9.99, 12.99, 14.99, 19.99):
        for cut, cutname in ((STORE_CUT_SMALL, "15%"), (STORE_CUT_STANDARD, "30%")):
            net = price * (1 - cut)
            rows.append((f"${price}", cutname,
                         f"{net/chapter_cost():.0f}",
                         f"{net/chapter_cost(6, 3):.0f}"))
    table("Break-even chapters per month", rows,
          ["Price/mo", "Store cut", "8pg/8img", "6pg/3img"])

    # 4. Price x cap sweep at the ADR-0002 shape, so the recommendation is
    #    chosen from data rather than asserted.
    rows = []
    for price in (12.99, 14.99):
        for cap in (12, 16, 20):
            for cut, cutname in ((STORE_CUT_SMALL, "15%"), (STORE_CUT_STANDARD, "30%")):
                net, cost, gross, pct = margin(
                    price, cap, cut, pages=PAGES_DEFAULT, images=IMAGES_DEFAULT)
                rows.append((f"${price}", cap, cutname, f"${cost:.2f}",
                             f"${gross:.2f}", f"{pct*100:.0f}%"))
    table("ADR-0002 shape (6 pages / 4 images): price x cap, worst case", rows,
          ["Price/mo", "Cap", "Store cut", "Cost", "Gross", "Margin"])

    # 5. What the open-weights path would buy, if it lands at the target.
    rows = []
    for images in (4,):
        now = chapter_cost(PAGES_DEFAULT, images)
        then = chapter_cost(PAGES_DEFAULT, images, image_cost=IMAGE_COST_OPENWEIGHTS_TARGET)
        for cap in (20, 30):
            for label, c in (("Nano Banana", now), ("open weights (target)", then)):
                net = 12.99 * (1 - STORE_CUT_STANDARD)
                gross = net - c * cap
                rows.append((label, cap, f"${c:.3f}", f"${gross:.2f}",
                             f"{gross/net*100:.0f}%"))
    table("Open-weights prize at $12.99, 30% store cut (UNMEASURED target)", rows,
          ["Image path", "Cap", "$/chapter", "Gross", "Margin"])

    # 6. Recommended shape at recommended price.
    print("\n### Recommended configuration\n")
    PRICE, INCLUDED, PAGES, IMAGES = 14.99, 20, PAGES_DEFAULT, IMAGES_DEFAULT
    for cut, cutname in ((STORE_CUT_SMALL, "15%"), (STORE_CUT_STANDARD, "30%")):
        net, cost, gross, pct = margin(PRICE, INCLUDED, cut, pages=PAGES, images=IMAGES)
        print(f"- ${PRICE}/mo, {INCLUDED} chapters included, {PAGES} pages / "
              f"{IMAGES} images: store cut {cutname} → net ${net:.2f}, "
              f"worst-case cost ${cost:.2f}, **gross ${gross:.2f} ({pct*100:.0f}%)**")
    typical = 12
    for cut, cutname in ((STORE_CUT_SMALL, "15%"),):
        net, cost, gross, pct = margin(PRICE, typical, cut, pages=PAGES, images=IMAGES)
        print(f"- Same plan at a TYPICAL {typical} chapters/mo: cost ${cost:.2f}, "
              f"**gross ${gross:.2f} ({pct*100:.0f}%)**")

    # 7. Free tier.
    print("\n### Free tier\n")
    for n in (1, 2, 3, 5):
        print(f"- {n} chapter(s): ${chapter_cost(PAGES, IMAGES)*n:.2f} "
              f"acquisition cost per signup")

    # 8. Keepsake print upgrade.
    print("\n### Keepsake re-render (Nano Banana Pro)\n")
    for chapters in (10, 20, 30):
        c = chapters * IMAGES * IMAGE_COST_PRO
        print(f"- {chapters}-chapter volume re-rendered at Pro: ${c:.2f} images")
