import * as React from 'react';

import { cleanup, screen, setup, waitFor } from '@/lib/test-utils';
import { ChapterReviewScreen } from './chapter-review-screen';

/**
 * AI-content labeling (issue #12): a parent deciding whether to approve a
 * chapter should see, plainly, that it was AI-generated — before they
 * decide, not just after.
 */

const mockGetChapterForReview = jest.fn();
const mockSetChapterApproval = jest.fn();
const mockSignImagePaths = jest.fn();

jest.mock('expo-router', () => ({
  useLocalSearchParams: () => ({ id: 'chapter-1' }),
  useRouter: () => ({ back: jest.fn() }),
}));

jest.mock('@/lib/supabase/chapters', () => ({
  getChapterForReview: (...args: unknown[]) => mockGetChapterForReview(...args),
  setChapterApproval: (...args: unknown[]) => mockSetChapterApproval(...args),
  signImagePaths: (...args: unknown[]) => mockSignImagePaths(...args),
}));

afterEach(() => {
  cleanup();
  jest.clearAllMocks();
});

describe('chapterReviewScreen — AI-content labeling', () => {
  it('shows a bilingual AI-generated notice before the parent decides', async () => {
    mockGetChapterForReview.mockResolvedValue({
      id: 'chapter-1',
      title_en: 'The Quiet Forest',
      title_ko: '조용한 숲',
      lesson: null,
      pages: [],
      review_status: 'pending',
      safety: { verdict: 'safe', concerns: [] },
    });
    mockSignImagePaths.mockResolvedValue({});

    setup(<ChapterReviewScreen />);

    expect(await screen.findByTestId('ai-generated-notice')).toBeOnTheScreen();
    expect(
      screen.getByText(/this chapter's text and pictures were generated by AI\./),
    ).toBeOnTheScreen();
    expect(
      screen.getByText('AI로 만들었어요 — 이 이야기의 글과 그림은 AI가 만들었어요.'),
    ).toBeOnTheScreen();

    // Not yet approved, so it must not claim a parent already reviewed it.
    await waitFor(() => expect(screen.getByTestId('approve')).toBeOnTheScreen());
    expect(screen.queryByText(/reviewed by a parent/)).not.toBeOnTheScreen();
  });
});
