import { Text, View } from '@/components/ui';

type AiGeneratedNoticeProps = {
  /** Which language renders first. Defaults to English for screens (like
   * the parent-preview) that don't yet know the child's primary_language. */
  lead?: 'en' | 'ko';
  /** True once a parent has approved the chapter — before that, "reviewed
   * by a parent" would be a claim the screen can't back up yet. */
  reviewed?: boolean;
};

/**
 * The AI-content label (issue #12): calm and unobtrusive, not a warning
 * banner — this is a trust feature. Appears on the parent-preview screen
 * (before approval) and in the reader (after), bilingual either way.
 */
export function AiGeneratedNotice({ lead = 'en', reviewed = false }: AiGeneratedNoticeProps) {
  const en = reviewed
    ? 'Made with AI — text and pictures generated by AI, reviewed by a parent.'
    : 'Made with AI — this chapter\'s text and pictures were generated by AI.';
  const ko = reviewed
    ? 'AI로 만들었어요 — 글과 그림을 AI가 만들었고, 부모님이 확인했어요.'
    : 'AI로 만들었어요 — 이 이야기의 글과 그림은 AI가 만들었어요.';

  return (
    <View
      testID="ai-generated-notice"
      className="gap-1 rounded-md bg-neutral-100 px-3 py-2 dark:bg-neutral-800"
    >
      <Text className="text-xs text-neutral-600 dark:text-neutral-400">
        {lead === 'ko' ? ko : en}
      </Text>
      <Text className="text-xs text-neutral-500">
        {lead === 'ko' ? en : ko}
      </Text>
    </View>
  );
}
