import * as React from 'react';

import { cleanup, screen, setup } from '@/lib/test-utils';
import { AiGeneratedNotice } from './ai-generated-notice';

afterEach(cleanup);

describe('aiGeneratedNotice (issue #12)', () => {
  it('states both languages regardless of lead', () => {
    setup(<AiGeneratedNotice lead="en" />);

    expect(
      screen.getByText(/Made with AI — this chapter's text and pictures were generated by AI\./),
    ).toBeOnTheScreen();
    expect(
      screen.getByText('AI로 만들었어요 — 이 이야기의 글과 그림은 AI가 만들었어요.'),
    ).toBeOnTheScreen();
  });

  it('does not claim a parent reviewed it before that is true', () => {
    setup(<AiGeneratedNotice />);

    expect(screen.queryByText(/reviewed by a parent/)).not.toBeOnTheScreen();
    expect(screen.queryByText(/부모님이 확인했어요/)).not.toBeOnTheScreen();
  });

  it('states the parent-reviewed fact once a chapter has been approved', () => {
    setup(<AiGeneratedNotice lead="ko" reviewed />);

    expect(
      screen.getByText('AI로 만들었어요 — 글과 그림을 AI가 만들었고, 부모님이 확인했어요.'),
    ).toBeOnTheScreen();
    expect(
      screen.getByText(/Made with AI — text and pictures generated by AI, reviewed by a parent\./),
    ).toBeOnTheScreen();
  });
});
