/**
 * Bumping this is what makes a parent who already consented get asked again
 * (`families.privacy_consent_version`, migration 0009). Keep it in sync with
 * the "Version:" line at the top of docs/privacy-policy.md, which is the
 * source-of-record text this screen renders a plain-language version of.
 */
export const PRIVACY_POLICY_VERSION = '2026-08-29';

export type PrivacySection = {
  heading_en: string;
  heading_ko: string;
  body_en: string;
  body_ko: string;
};

export type ConsentItem = {
  en: string;
  ko: string;
};

/**
 * The PIPA-shaped consent step at onboarding (issue #12): separate, specific,
 * and informed, not one checkbox bundled with terms-of-service boilerplate.
 * Kept to one line each — "one clear screen, warm copy, not a legal dump" —
 * with the full text one tap away via the /privacy screen.
 */
export const ONBOARDING_CONSENT_ITEMS: ConsentItem[] = [
  {
    en: 'Items collected: your child\'s name, age, language, interests, and the situations you describe for their stories.',
    ko: '수집 항목: 아이의 이름, 나이, 언어, 관심사, 그리고 이야기를 위해 적어주신 상황.',
  },
  {
    en: 'Purpose: writing and illustrating your child\'s bedtime stories, which you review before they\'re shown.',
    ko: '이용 목적: 아이의 동화를 쓰고 그리는 것이며, 보여드리기 전에 부모님이 먼저 확인해요.',
  },
  {
    en: 'Retention: stored in our database (Supabase). Exact retention period not yet set — see the full notice.',
    ko: '보유 기간: 저희 데이터베이스(Supabase)에 저장돼요. 정확한 보유 기간은 아직 정해지지 않았어요 — 전체 고지 참고.',
  },
  {
    en: 'Cross-border transfer: what you type is sent to Anthropic and Google, in the United States, to generate the story and pictures.',
    ko: '국외 이전: 입력하신 내용은 이야기와 그림 생성을 위해 미국의 Anthropic과 Google로 전송돼요.',
  },
  {
    en: 'Your right to refuse: you can decline, but we then can\'t create a profile or generate stories for your account.',
    ko: '거부 권리: 동의하지 않으실 수 있어요. 다만 그 경우 프로필 생성과 이야기 생성이 불가능해요.',
  },
];

/**
 * A plain-language in-app rendering of docs/privacy-policy.md, not a literal
 * copy of the full legal text — a tired parent reads this, not the markdown
 * file. Anywhere the source doc has a TODO(Jai) placeholder, this copy says
 * so plainly rather than inventing a value.
 */
export const PRIVACY_SECTIONS: PrivacySection[] = [
  {
    heading_en: 'What we collect',
    heading_ko: '저희가 수집하는 정보',
    body_en:
      'Your account email; your child\'s first name, age band, language, and interests; the situations you describe for a chapter (including sensitive things like a fear, a grief, or a family change, if you share them); the chapters and illustrations we generate; and, only if you order a hardcover, a real name and shipping address.',
    body_ko:
      '로그인용 계정 이메일, 아이의 이름과 연령대·언어·관심사, 챕터를 위해 적어주신 상황(두려움, 슬픔, 가족의 변화 등 민감한 내용을 나눠주신 경우 포함), 생성된 챕터와 삽화, 그리고 하드커버를 주문하신 경우에만 실제 이름과 배송 주소입니다.',
  },
  {
    heading_en: 'Chapters are AI-generated',
    heading_ko: '챕터는 AI가 만들어요',
    body_en:
      'Every chapter\'s text and every illustration is generated by AI, not written or drawn by a person. You see and approve each one before your child can read it.',
    body_ko:
      '모든 챕터의 글과 삽화는 사람이 아닌 AI가 만들어요. 아이가 읽기 전에 부모님이 먼저 확인하고 승인해요.',
  },
  {
    heading_en: 'Third-party AI providers',
    heading_ko: '제3자 AI 제공업체',
    body_en:
      'What you type is sent to third-party AI companies to generate the story: Anthropic (Claude models) writes the text, and Google (Gemini models) generates the illustrations. This means it leaves our servers and the country — processed in the United States — before the story comes back to you.',
    body_ko:
      '입력하신 내용은 이야기를 만들기 위해 제3자 AI 회사로 전송됩니다: Anthropic(Claude 모델)이 텍스트를, Google(Gemini 모델)이 삽화를 생성해요. 즉 저희 서버와 국가를 벗어나 미국에서 처리된 뒤 이야기로 돌아옵니다.',
  },
  {
    heading_en: 'Cross-border transfer (Korea PIPA)',
    heading_ko: '국외 이전 (개인정보보호법)',
    body_en:
      'Recipient: Anthropic (text), Google (images). Country: United States. Items: the situation/character text you type. Purpose: generating your child\'s story and illustrations. Retention by the recipient: not yet confirmed (TODO for Jai).',
    body_ko:
      '제공받는 자: Anthropic(텍스트), Google(이미지). 이전 국가: 미국. 이전 항목: 입력하신 상황/캐릭터 텍스트. 이전 목적: 아이의 이야기와 삽화 생성. 제공받는 자의 보유 기간: 아직 확인되지 않음 (Jai 확인 필요).',
  },
  {
    heading_en: 'Where it\'s stored, and for how long',
    heading_ko: '저장 위치와 보관 기간',
    body_en:
      'Everything above is stored in our database, hosted on Supabase. The exact retention period has not been decided yet (TODO for Jai).',
    body_ko:
      '위 정보는 Supabase에 호스팅된 데이터베이스에 저장돼요. 정확한 보관 기간은 아직 결정되지 않았어요 (Jai 확인 필요).',
  },
  {
    heading_en: 'Your right to refuse',
    heading_ko: '동의 거부 권리',
    body_en:
      'You can decline this notice. If you do, we cannot create a child profile or generate any chapters for your account, since that requires sending story details to the providers above. Declining does not affect your ability to delete your account.',
    body_ko:
      '이 고지에 동의하지 않으실 수 있어요. 다만 동의하지 않으시면 아이 프로필을 만들거나 챕터를 생성할 수 없어요. 동의를 거부해도 계정 삭제 권리에는 영향이 없어요.',
  },
  {
    heading_en: 'Deleting your data',
    heading_ko: '정보 삭제',
    body_en:
      'You can ask us to delete your child\'s profile and every chapter and image associated with it. The exact deletion mechanism and turnaround time are not built yet (TODO for Jai) — contact us using the address below in the meantime.',
    body_ko:
      '아이의 프로필과 관련된 모든 챕터·이미지 삭제를 요청하실 수 있어요. 실제 삭제 방법과 처리 기한은 아직 마련되지 않았어요 (Jai 확인 필요) — 그동안은 아래 연락처로 문의해 주세요.',
  },
  {
    heading_en: 'Contact',
    heading_ko: '문의처',
    body_en:
      'Legal entity name, address, and a privacy contact / person in charge of personal data under PIPA (개인정보보호책임자) have not been filled in yet (TODO for Jai).',
    body_ko:
      '법인명, 주소, 그리고 PIPA상 개인정보보호책임자 연락처가 아직 채워지지 않았어요 (Jai 확인 필요).',
  },
];
